name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'

      - name: Install Dependncies
        run:  sudo npm install
      
      - name: tshirts fail
        run: node tests/tshirts.test.js

      - name: misaligned fail
        run: node tests/misaligned.test.js

      - name: transmitter fail
        run: node tests/transmitter.test.js
